### ISSUE TITLE
[PE-D][Tester D] Parser Error when using the 'filter' command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113T-W11-2/tp#104]
![Screenshot 2022-10-28 at 5.11.12 PM.png](https://raw.githubusercontent.com/yongjicode/ped/main/files/221f4cde-e384-491d-8f39-6a5be2586d6f.png)

Tried to filter for price but did not put in the range for it, resulted in some parser error. Did not handle the error properly for this part.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yongjicode/ped#3

**Comment by P0tatoChips** [comment]
throw ArrayIndexOutOfBoundsException with function and caught it in the parse method
refer to #125 Minor bug fix
