### ISSUE TITLE
[PE-D][Tester C] Able to add Price larger than MAX_VALUE of int

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113T-W11-2/tp#111]
![Bug10.JPG](https://raw.githubusercontent.com/brian-vb/ped/main/files/e1252914-8d4b-4ccc-84eb-acc705279384.JPG)

There are checks put in place for Power Consumption but not for price.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: brian-vb/ped#10

**Comment by GitPancaked** [comment]
We don't feel this is an issue as from a realistic pov we highly doubt our target audience would add a component that costs more than 2billion dollars.
