### ISSUE TITLE
[PE-D][Tester C] Able to add Clock Speed larger than MAX_VALUE of int

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113T-W11-2/tp#114]
![Bug11.JPG](https://raw.githubusercontent.com/brian-vb/ped/main/files/c6f3cbeb-dd94-470e-b66d-faa1e540142c.JPG)

There are checks put in place for Power Consumption but not for this.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: brian-vb/ped#11

**Comment by P0tatoChips** [comment]
Clock speed is not stored as an int. No issue anyway as we never use it for any features
