### ISSUE TITLE
[PE-D][Tester B] Filter Command corner case not handled

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113T-W11-2/tp#116]
![Screenshot 2022-10-28 at 5.29.22 PM.png](https://raw.githubusercontent.com/NayChi-7/ped/main/files/55d9b519-d780-40cf-9b4e-0a36c3c0e37f.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: NayChi-7/ped#7

**Comment by P0tatoChips** [comment]
throw ArrayIndexOutOfBoundsException with function and caught it in the parse method
Fixed in #125 Minor bug fix, cant add this through github
