### ISSUE TITLE
[PE-D][Tester A] Ambiguity in the 'type' when filtering builds

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113T-W11-2/tp#117]
UG should be more specific and elaborate about the different types that the builds can be filtered by and the command to input to filter them. Based on the description, it can be filtered by compatibility or total cost/power within a specified range but what is the keyword for filtering by total cost/power?

-------------
Labels: `severity.High` `type.DocumentationBug`
original: JordanKwua/ped#9

**Comment by lcsroy** [comment]
Shown all 3 different types as acceptable formats for easier reference for the user.
