### ISSUE TITLE
Some comments/suggestions on your DG

### ISSUE THREAD

**Issue by okkhoy** [AY2223S1-CS2113T-W11-2/tp#122]
1. Please update/remove these sections before the final version. Don't retain template text
![image](https://user-images.githubusercontent.com/1023494/198888668-bdac1b5e-20c2-4de9-986e-a8d91603a9ee.png)

2. Pls give a brief overview of the product here too (maybe copy-paste from the UG)

3. Two issues here (common to other class diagrams as well) 
![image](https://user-images.githubusercontent.com/1023494/198888768-b2c57605-00b7-4b12-bbaa-1c43cd551ebe.png)
   i. Pls remove the (C) icon -- it is not standard UML
   ii. Please omit trivial methods (and/or methods that are not directly relevant to the preceding/succeeding discussions) to keep the diagram clean.

4. Needs "closing" the activation
![image](https://user-images.githubusercontent.com/1023494/198888866-97d3e0ec-3f1f-417b-812e-031ef7446703.png)

5. Need colon to indicate these are entities
![image](https://user-images.githubusercontent.com/1023494/198889075-b2e13e20-3d53-45ce-9f72-0387292cebc7.png)

5. `Many` should be `*` (or the number/range)
![image](https://user-images.githubusercontent.com/1023494/198888894-644fa880-3bfc-45dc-a4b6-3ebc8cffc425.png)

7. Simplify/split diagram to a few parts
![image](https://user-images.githubusercontent.com/1023494/198888952-e5e8cef5-4551-4bf7-812c-ef5dd94442fe.png)
When you print to PDF, we can't see anything in the diagram and it could end up being a doc bug!

8. May be better to indicate **explicitly** somehow that the user story will be implemented in the version specified 
![image](https://user-images.githubusercontent.com/1023494/198889037-a370d22c-ff42-495f-8593-5cb41f1668af.png)

**Comment by GitPancaked** [comment]
Thank you for the suggestions Prof, we have rectified these issues in our DG accordingly.
