### ISSUE TITLE
[PE-D][Tester C] Incorrect Instruction for Step 5 of UG (Quick Start)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113T-W11-2/tp#91]
![Bug2.JPG](https://raw.githubusercontent.com/brian-vb/ped/main/files/e9794127-6dfd-460b-89c8-6c2770de04af.JPG)

The downloaded jar file is tp.jar

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: brian-vb/ped#6

**Comment by GitPancaked** [comment]
fixed CCC.jar to tp.jar
