### ISSUE TITLE
[PE-D][Tester A] Instructions unclear for edit mode

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113T-W11-2/tp#93]
From what I understand about the code based on the manual testing I have done, it is not possible to use Main Mode functionalities in Edit Mode but it is not stated specifically and the error message which is "Please input a valid command" seems very vague. Should elaborate further that Main Mode functionalities don't work in Edit Mode.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: JordanKwua/ped#1

**Comment by GitPancaked** [comment]
We have made this clearer by changing visual aspects of the printed lines for edit Mode and main Mode
